const challenges=[{title:'Improve a broad science prompt',type:'Prompt improvement',description:'Rewrite the prompt so an AI gives a useful answer for a middle school learner.',original:'Tell me about space.',expected:['audience','format','specific topic','length']},{title:'Improve a creative writing prompt',type:'Prompt improvement',description:'Add enough detail for the AI to write a focused, age-appropriate story.',original:'Write a story.',expected:['genre','character','setting','conflict']},{title:'Create a homework timetable prompt',type:'Prompt creation',description:'Create a prompt that asks AI to build a practical homework timetable.',original:'Your prompt should generate a weekly homework timetable.',expected:['subjects','time','format','constraints']},{title:'Create an image generation prompt',type:'Prompt creation',description:'Describe a dragon clearly enough for an image model to create it.',original:'Your prompt should describe a dragon image.',expected:['visual details','style','setting','composition']},{title:'Design a real-world problem prompt',type:'Final challenge',description:'Write a prompt that helps solve a real problem at home, school, or in the community.',original:'Choose a real-world problem and design a responsible AI prompt.',expected:['problem','context','steps','responsible use']}];
const state={screen:'landing',current:0,studentName:'Student',startedAt:null,completed:false,results:[],sound:false,theme:'light'};
const $=id=>document.getElementById(id);
function save(){localStorage.setItem('aiAdventureState',JSON.stringify(state));}
function load(){const saved=localStorage.getItem('aiAdventureState');if(saved){Object.assign(state,JSON.parse(saved));}}
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');state.screen=id;save();}
function typeIntro(){const text='You are entering a virtual AI training environment. To complete the mission, solve prompt engineering challenges by making your instructions clearer, more specific, and more responsible.';const target=$('typingStory');target.textContent='';let i=0;const tick=()=>{target.textContent=text.slice(0,i++);if(i<=text.length)setTimeout(tick,18)};tick();}
function renderChallenge(){const c=challenges[state.current];$('challengeTitle').textContent=c.title;$('challengeType').textContent=c.type;$('challengeDescription').textContent=c.description;$('originalPrompt').textContent=c.original;$('promptInput').value=state.results[state.current]?.prompt||'';$('scoreCard').hidden=true;$('nextButton').disabled=true;const pct=Math.round(((state.current+1)/challenges.length)*100);$('challengeCounter').textContent=`Challenge ${state.current+1} of ${challenges.length}`;$('progressPercent').textContent=`${pct}%`;$('progressBar').style.width=`${pct}%`;}
function wordCount(text){return text.trim().split(/\s+/).filter(Boolean).length;}
function includesAny(text,terms){return terms.some(t=>text.includes(t));}
function scorePrompt(prompt,challenge){const text=prompt.toLowerCase();const words=wordCount(prompt);const clarity=Math.min(10,Math.round((/[?.]$/.test(prompt.trim())?2:0)+(words>=12?3:1)+(includesAny(text,['create','write','explain','design','generate','make'])?2:0)+(includesAny(text,['for','to help','so that'])?3:1)));const context=Math.min(10,Math.round((includesAny(text,['grade','student','audience','class','middle school'])?3:0)+(includesAny(text,['because','background','context','problem','goal'])?3:0)+(challenge.expected.filter(t=>text.includes(t.split(' ')[0])).length*2)));const specificity=Math.min(10,Math.round((words>=25?3:words>=16?2:1)+(includesAny(text,['include','must','avoid','limit','use','with'])?2:0)+(includesAny(text,['table','list','paragraph','steps','bullets','format'])?3:0)+( /\d/.test(text)?2:0)));const creativity=Math.min(10,Math.round((includesAny(text,['creative','style','tone','imagine','visual','original'])?3:1)+(includesAny(text,['example','scenario','character','setting','real-world'])?3:0)+(words>=30?2:1)+(includesAny(text,['responsible','safe','ethical','accurate'])?2:0)));return {clarity,context,specificity,creativity};}
function feedback(scores,prompt){const tips=[];if(scores.context<7)tips.push('Try adding the audience, background, or purpose.');else tips.push('Excellent use of context.');if(scores.specificity<7)tips.push('Add constraints such as length, format, time, or required details.');else tips.push('Strong specificity makes the AI output easier to evaluate.');if(scores.clarity<7)tips.push('Make the action verb and expected outcome clearer.');if(scores.creativity>=8)tips.push('Your prompt encourages an original, thoughtful response.');if(!/table|list|bullet|steps|paragraph|format/i.test(prompt))tips.push('Specify the format so the result is classroom-ready.');return tips;}
function evaluate(){const prompt=$('promptInput').value.trim();if(!prompt){$('promptInput').focus();return;}const scores=scorePrompt(prompt,challenges[state.current]);const average=Math.round(Object.values(scores).reduce((a,b)=>a+b,0)/4);const result={prompt,scores,average,feedback:feedback(scores,prompt)};state.results[state.current]=result;save();renderScore(result);$('nextButton').disabled=false;playTone();updateDashboard();}
function renderScore(result){$('scoreCard').hidden=false;$('scoreCard').innerHTML=`<h2>Score card</h2><div class="metric-grid">${Object.entries(result.scores).map(([k,v])=>`<div class="metric"><span>${k[0].toUpperCase()+k.slice(1)}</span><strong>${v}/10</strong></div>`).join('')}</div><h3>Feedback</h3><ul class="feedback-list">${result.feedback.map(f=>`<li>${f}</li>`).join('')}</ul>`;}
function next(){if(state.current<challenges.length-1){state.current++;renderChallenge();showScreen('challengeScreen');}else complete();}
function complete(){state.completed=true;showScreen('completion');const avg=overallAverage();$('finalScore').textContent=`${avg}%`;$('strengthsList').innerHTML='<li>Clearer instructions for AI tools.</li><li>Growing use of context and format.</li>';$('improvementsList').innerHTML='<li>Keep adding measurable constraints.</li><li>Check whether AI answers are accurate and safe.</li>';confetti();updateDashboard();save();}
function overallAverage(){if(!state.results.length)return 0;return Math.round((state.results.reduce((s,r)=>s+(r?.average||0),0)/(challenges.length*10))*100);}
function updateDashboard(){const elapsed=state.startedAt?Math.floor((Date.now()-state.startedAt)/1000):0;$('dashScore').textContent=`${overallAverage()}%`;$('dashTime').textContent=`${Math.floor(elapsed/60)}:${String(elapsed%60).padStart(2,'0')}`;const avg=state.results.length?Math.round(state.results.reduce((s,r)=>s+(r?.average||0),0)/state.results.filter(Boolean).length):0;$('dashAverage').textContent=`${avg}/10`;$('dashChallenges').innerHTML=challenges.map((c,i)=>`<div><strong>${i+1}. ${c.title}</strong><br>${state.results[i]?state.results[i].average+'/10':'Not completed'}</div>`).join('');}
function playTone(){if(!state.sound)return;const ctx=new AudioContext();const osc=ctx.createOscillator();const gain=ctx.createGain();osc.connect(gain);gain.connect(ctx.destination);gain.gain.value=.04;osc.frequency.value=520;osc.start();setTimeout(()=>{osc.stop();ctx.close();},120);}
function confetti(){const canvas=$('confettiCanvas'),ctx=canvas.getContext('2d');canvas.width=innerWidth;canvas.height=innerHeight;const pieces=Array.from({length:90},()=>({x:Math.random()*canvas.width,y:-20-Math.random()*200,s:4+Math.random()*6,v:2+Math.random()*4,r:Math.random()*Math.PI}));let frames=0;function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle=getComputedStyle(document.body).getPropertyValue('--accent');pieces.forEach(p=>{p.y+=p.v;p.x+=Math.sin(p.y/25);p.r+=.05;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.r);ctx.fillRect(-p.s/2,-p.s/2,p.s,p.s);ctx.restore();});if(frames++<160)requestAnimationFrame(draw);else ctx.clearRect(0,0,canvas.width,canvas.height);}draw();}
function restart(){localStorage.removeItem('aiAdventureState');location.reload();}
function certificate(){state.studentName=$('studentName').value.trim()||state.studentName||'Student';$('certificateName').textContent=state.studentName;$('certificateDate').textContent=new Date().toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'});showScreen('certificate');}
function init(){load();setTimeout(()=>$('loadingScreen').classList.add('hidden'),650);$('startButton').onclick=()=>{showScreen('intro');typeIntro();};$('beginButton').onclick=()=>{state.studentName=$('studentName').value.trim()||'Student';state.startedAt=state.startedAt||Date.now();state.current=0;renderChallenge();showScreen('challengeScreen');};$('evaluateButton').onclick=evaluate;$('nextButton').onclick=next;$('certificateButton').onclick=certificate;$('restartButton').onclick=restart;$('printButton').onclick=()=>print();$('backCompletion').onclick=()=>showScreen('completion');$('teacherToggle').onclick=()=>{$('teacherDashboard').hidden=false;$('teacherToggle').setAttribute('aria-expanded','true');updateDashboard();};$('closeTeacher').onclick=()=>{$('teacherDashboard').hidden=true;$('teacherToggle').setAttribute('aria-expanded','false');};$('themeToggle').onclick=()=>{document.body.classList.toggle('dark');state.theme=document.body.classList.contains('dark')?'dark':'light';$('themeToggle').setAttribute('aria-pressed',state.theme==='dark');save();};$('soundToggle').onclick=()=>{state.sound=!state.sound;$('soundToggle').textContent=state.sound?'Sound On':'Sound Off';$('soundToggle').setAttribute('aria-pressed',state.sound);save();};if(state.theme==='dark')document.body.classList.add('dark');if(state.screen==='challengeScreen')renderChallenge();if(state.screen==='intro')typeIntro();if(state.screen==='completion')complete();showScreen(state.screen||'landing');setInterval(updateDashboard,1000);} 
document.addEventListener('DOMContentLoaded',init);
